# USAGE: use this configuration for loading the "web" image (with app.jar) as opposed to 
#  the "web-and-data" image. E.g.
#  'docker compose -f  docker-compose.yml -f docker-compose.web.yml up'

version: '3'

services:
  cbioportal:
    env_file:
      - path: ./.env
        required: false
    command: /bin/sh -c "
      java 
      -Xms2g 
      -Xmx4g 
      -jar /cbioportal-webapp/app.jar  
      --authenticate=false 
      --session.service.url=http://cbioportal-session:5001/api/sessions/my_portal/
      --db.user=$${DB_MYSQL_USERNAME}
      --db.password=$${DB_MYSQL_PASSWORD}
      --spring.datasource.driver-class-name=com.mysql.jdbc.Driver
      --spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
      --spring.datasource.url=$${DB_MYSQL_URL}
      --spring.datasource.username=$${DB_MYSQL_USERNAME}
      --spring.datasource.password=$${DB_MYSQL_PASSWORD}
      --spring.datasource.mysql.url=$${DB_MYSQL_URL}
      --spring.datasource.mysql.username=$${DB_MYSQL_USERNAME}
      --spring.datasource.mysql.password=$${DB_MYSQL_PASSWORD}
      --spring.datasource.mysql.driver-class-name=com.mysql.jdbc.Driver
      --spring.datasource.clickhouse.url=$${DB_CLICKHOUSE_URL}
      --spring.datasource.clickhouse.username=$${DB_CLICKHOUSE_USERNAME}
      --spring.datasource.clickhouse.password=$${DB_CLICKHOUSE_PASSWORD}
      --spring.datasource.clickhouse.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver
      --clickhouse_mode=$${APP_CLICKHOUSE_MODE:-false}
      $${APP_CUSTOM_ARGS}
      "
