name: Update Clickhouse Importer Docker Image

on:
  push:
    paths:
      - 'addon/clickhouse/importer.Dockerfile'
      - '.github/workflows/clickhouse-importer-docker-image.yml'

jobs:
  update-clickhouse-importer-image:
    runs-on: ubuntu-latest
    if: github.repository == 'cbioportal/cbioportal-docker-compose'
    env:
      DOCKERHUB_REPO: 'cbioportal/clickhouse-importer'
      PLATFORMS: 'linux/amd64,linux/arm64'
      GIT_OWNER: 'cbioportal'
      GIT_REPO: 'cbioportal-core'
      GIT_BRANCH: 'main'
      GIT_COMMIT: 'c36948564d85cdb83520021ac75426a2a451e4ce'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.GIT_COMMIT }}
          build-args: |
            OWNER=${{ env.GIT_OWNER }}
            REPO=${{ env.GIT_REPO }}
            BRANCH=${{ env.GIT_BRANCH }}
            COMMIT=${{ env.GIT_COMMIT }}
          platforms: ${{ env.PLATFORMS }}
          file: addon/clickhouse/importer.Dockerfile
          cache-from: type=gha
          cache-to: type=gha
